[helpers]

[default]
depends = []

[default.files]

# environment.d
"environment.d" = "~/.config/environment.d"

# shell
"zsh/.zshrc" = "~/.zshrc"
fish = "~/.config/fish"
"starship/starship.toml" = "~/.config/starship.toml"

# terminal
ghostty = "~/.config/ghostty"

# niri
niri = "~/.config/niri"

# nvim
nvim = "~/.config/nvim"

# DankShell
DankMaterialShell = "~/.config/DankMaterialShell"
dgop = "~/.config/dgop"

# im
fcitx = "~/.config/fcitx"
fcitx5 = "~/.config/fcitx5"
rime = "~/.local/share/fcitx5/rime"

fastfetch = "~/.config/fastfetch"

fontconfig = "~/.config/fontconfig"

"gtk-3.0" = "~/.config/gtk-3.0"
"gtk-4.0" = "~/.config/gtk-4.0"

opencode = "~/.config/opencode"

[default.variables]

[settings]
default_target_type = "automatic"
