[helpers]

[default]
depends = []

[default.files]

# shell
"zsh/.zshrc" = "~/.zshrc"
fish = "~/.config/fish"
"starship/starship.toml" = "~/.config/starship.toml"

# terminal
kitty = "~/.config/kitty"
ghostty = "~/.config/ghostty"
foot = "~/.config/foot"

# niri
niri = "~/.config/niri"

fastfetch = "~/.config/fastfetch"
btop = "~/.config/btop"

# nvim
nvim = "~/.config/nvim"

# DankShell
DankMaterialShell = "~/.config/DankMaterialShell"
dgop = "~/.config/dgop"

fcitx5 = "~/.config/fcitx5"
fontconfig = "~/.config/fontconfig"

# solatar
solaar = "~/.config/solaar"

[settings]
default_target_type = "automatic"
